services:
  aiocatalogs:
    container_name: aiocatalogs
    restart: unless-stopped

    # Build the image from the Dockerfile
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # image: aiocatalogs

    # Or use the pre-built image from GitHub Container Registry
    image: ghcr.io/pantelx/aiocatalogs:latest
    ports:
      - '8787:8787'
    environment:
      - PORT=8787
    volumes:
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules
